name: GetDataBase
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # star and watch events
  watch:
    types: [started]
    

jobs:
  builds:
    name: GetDataBase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
           python-version: 3.7

      - name: 'Install requirements'
        run: |
          pip install -r ./requirements.txt

      - name: 'Run Bing API'
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ./main.py

      - name: "POST to Redis"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python ./post_to_redis.py
          
      - name: Commit files
        run: |
          git config --local user.email "admin@icodeq.com"
          git config --local user.name "zkeq"
          git add .
          git commit -m "update bing daily data"
      - name: Push changes
        uses:  ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_GIT_TOKEN }}
          branch: main
